name: Experiment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  my-job:
    runs-on: ubuntu-latest


    steps:
      - name: Get current git tag
        uses: devops-actions/action-get-tag@v1.0.2
      - name: Step 2
        run: |
          # Use the TAG_NAME environment variable
          echo "The tag name is: ${{steps.tag.outputs.tag}} "
