name: Docker Image CI
on:
  workflow_dispatch:
    inputs:
      dependency-workflow:
        description: 'The workflow dependency to use'
        required: true
        default: 'Java CI with Maven'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # 下载构建工件
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: cloudeon-assembly-1.0.0-release.tar.gz
        path: ./docker/cloudeon-assembly-1.0.0-release.tar.gz
    - name: Build the Docker image
      run: tar zxvf ./docker/cloudeon-assembly-1.0.0-release.tar.gz -C  ./docker
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: perterpoker/cloudeon
        tag_with_ref: true
        tags: latest
        path: docker/
