name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: mvn clean install  -DskipTests  && cp -r cloudeon-assembly/target/cloudeon-assembly-1.0.0-release docker/
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: perterpoker/cloudeon
        tag_with_ref: true
        tags: latest
        path: docker/
