name: Maven Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1
        with:
          strip_v: false # Optional: Remove 'v' character from version
          default: v0.0.0 # Optional: Default version when tag not found

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn  clean install  -DskipTests
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_TOKEN }}
        with:
          tag_name: ${{steps.tag.outputs.tag}}
          release_name: Release ${{steps.tag.outputs.tag}}
          body: |
            This is a release for version  ${{steps.tag.outputs.tag}}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_TOKEN }}
          TAG_NAME: ${{steps.tag.outputs.tag}}

        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cloudeon-assembly/target/cloudeon-assembly-${TAG_NAME}-release.tar.gz
          asset_name: cloudeon-assembly-${TAG_NAME}-release.tar.gz
          asset_content_type: application/gzip